services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres
  redis:
    image: redis:latest
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  express-server:
    build:
      dockerfile: Dockerfile.dev
      context: ./express-server
    volumes:
      - /app/node_modules
      - ./express-server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres_password
      - PG_DATABASE=postgres
    depends_on:
      - postgres
      - redis
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
